additionalProperties:
  moduleName: Propertyware
  gemAuthor: LeadSimple
  gemHomepage: https://github.com/LeadSimple/propertyware
  gemDescription: API client library for Propertyware
  gemRequiredRubyVersion: "> 2.6.0"
  gemVersion: 1.1.0
