=begin
#Open API, powered by Propertyware


The version of the OpenAPI document: 1.0
Contact: support@propertyware.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Propertyware::BuildingsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BuildingsApi' do
  before do
    # run before each test
    @api_instance = Propertyware::BuildingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BuildingsApi' do
    it 'should create an instance of BuildingsApi' do
      expect(@api_instance).to be_instance_of(Propertyware::BuildingsApi)
    end
  end

  # unit tests for create_building
  # Create a building
  # Creates a building.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param save_building saveBuilding
  # @param [Hash] opts the optional parameters
  # @return [Building]
  describe 'create_building test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_contacts
  # Create buildings in bulk
  # Creates buildings in bulk.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param save_building saveBuilding
  # @param [Hash] opts the optional parameters
  # @return [Array<RESTAPIBulkSuccessResponse>]
  describe 'create_contacts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_building
  # Delete a building (BETA)
  # &lt;p class&#x3D;\&quot;betaError\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;Write access is only available to customers who have opted in to our beta program. Please reach out to support if you&#39;d like to be included.&lt;/p&gt; Delete a building.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Delete&lt;/code&gt; 
  # @param building_id Building ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'delete_building test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_building_conversation
  # Delete a building conversation (BETA)
  # &lt;p class&#x3D;\&quot;betaError\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;Write access is only available to customers who have opted in to our beta program. Please reach out to support if you&#39;d like to be included.&lt;/p&gt; Deletes a specific building conversation.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Delete&lt;/code&gt; 
  # @param building_id Building ID
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'delete_building_conversation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_building
  # Retrieve a building
  # Retrieves a specific building.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param building_id Building ID
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_custom_fields Include custom fields in the response.
  # @return [Building]
  describe 'get_building test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_building_conversation
  # Retrieve a building conversation
  # Retrieves a specific building conversation.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param building_id Building ID
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [Conversation]
  describe 'get_building_conversation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_building_conversations
  # Retrieve all building conversations
  # Retrieves all the conversations of a building.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; &lt;br/&gt;&lt;br/&gt;&lt;b&gt;Sortable by:&lt;/b&gt; &lt;code&gt;createddate&lt;/code&gt;, &lt;code&gt;lastmodifieddatetime&lt;/code&gt;, &lt;code&gt;id&lt;/code&gt;
  # @param building_id Building ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset &#x60;offset&#x60; indicates the position of the first record to return. The offset is zero-based and the default is 0.
  # @option opts [Integer] :limit &#x60;limit&#x60; indicates the maximum number of results to be returned in the response. &#x60;limit&#x60; can range between 1 and 500 and the default is 100.
  # @option opts [Time] :last_modified_date_time_start Filters results to any item modified on or after the date time specified. 
  # @option opts [Time] :last_modified_date_time_end Filters results to any item modified on or prior to the date time specified. 
  # @option opts [String] :orderby Indicates the field(s) and direction to sort the results in the response.
  # @option opts [String] :type Filters results by the conversation type.
  # @return [Array<Conversation>]
  describe 'get_building_conversations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_building_management_fee
  # Retrieves all the management fee rules of a building. (BETA)
  # &lt;p class&#x3D;\&quot;betaWarning\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;This operation is still in beta and might be subject to breaking changes. Production integrations should be avoided at this stage.&lt;/p&gt; Retrieves all the management fee rules of a building.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param building_id Building ID
  # @param [Hash] opts the optional parameters
  # @return [Array<ManagementFee>]
  describe 'get_building_management_fee test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_building_managers
  # Retrieves all the property managers of a building
  # Retrieves all the property managers of a building.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param building_id Building ID
  # @param [Hash] opts the optional parameters
  # @return [Array<PropertyManager>]
  describe 'get_building_managers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_building_notes
  # Retrieves all the notes of a building.
  # Retrieves all the notes of a building.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param building_id Building ID
  # @param [Hash] opts the optional parameters
  # @return [Array<Note>]
  describe 'get_building_notes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_buildings
  # Retrieve all buildings
  # Retrieves a list of buildings.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; &lt;br/&gt;&lt;br/&gt;&lt;b&gt;Sortable by:&lt;/b&gt; &lt;code&gt;createddate&lt;/code&gt;, &lt;code&gt;idnumber&lt;/code&gt;, &lt;code&gt;name&lt;/code&gt;, &lt;code&gt;abbreviation&lt;/code&gt;, &lt;code&gt;lastmodifieddatetime&lt;/code&gt;, &lt;code&gt;id&lt;/code&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset &#x60;offset&#x60; indicates the position of the first record to return. The offset is zero-based and the default is 0.
  # @option opts [Integer] :limit &#x60;limit&#x60; indicates the maximum number of results to be returned in the response. &#x60;limit&#x60; can range between 1 and 500 and the default is 100.
  # @option opts [Time] :last_modified_date_time_start Filters results to any item modified on or after the date time specified. 
  # @option opts [Time] :last_modified_date_time_end Filters results to any item modified on or prior to the date time specified. 
  # @option opts [String] :orderby Indicates the field(s) and direction to sort the results in the response.
  # @option opts [Boolean] :vacant Filters results by the building&#39;s vacancy status. If no value is specified, buildings with any status will be returned.
  # @option opts [Boolean] :published_for_rent Filters results by the building&#39;s \&quot;published for rent\&quot; status. If no value is specified, buildings with any status will be returned.
  # @option opts [Integer] :lease_id Filters results to buildings associated with a specific lease.
  # @option opts [Integer] :portfolio_id Filters results to buildings associated with a specific portfolio.
  # @option opts [Boolean] :include_deactivated Filters results to buildings with a deactivated records.
  # @option opts [Boolean] :include_custom_fields Include custom fields in the response.
  # @return [Array<Building>]
  describe 'get_buildings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_building
  # Update a building custom fields (BETA)
  # &lt;p class&#x3D;\&quot;betaError\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;Write access is only available to customers who have opted in to our beta program. Please reach out to support if you&#39;d like to be included.&lt;/p&gt; Updates an existing building custom fields&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param save_custom_field saveCustomField
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'update_building test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_building_using_put1
  # Update a building
  # Updates a building.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;BUILDINGS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param building_id Building ID
  # @param update_building updateBuilding
  # @param [Hash] opts the optional parameters
  # @return [Building]
  describe 'update_building_using_put1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
