=begin
#Open API, powered by Propertyware


The version of the OpenAPI document: 1.0
Contact: support@propertyware.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Propertyware::DocumentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DocumentsApi' do
  before do
    # run before each test
    @api_instance = Propertyware::DocumentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DocumentsApi' do
    it 'should create an instance of DocumentsApi' do
      expect(@api_instance).to be_instance_of(Propertyware::DocumentsApi)
    end
  end

  # unit tests for delete_document
  # Delete a document (BETA)
  # &lt;p class&#x3D;\&quot;betaError\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;Write access is only available to customers who have opted in to our beta program. Please reach out to support if you&#39;d like to be included.&lt;/p&gt; Deletes a specific document and its associated content.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;DOCUMENTS&lt;/span&gt; - &lt;code&gt;Delete&lt;/code&gt; 
  # @param document_id ID of the document to delete
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'delete_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for download_document
  # Download a document
  # Retrieve a temporary download URL for a specific document.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;DOCUMENTS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param document_id ID of the document to download
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'download_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_all_documents
  # Retrieve all documents
  # Retrieves a list of documents associated with a specific entity.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;DOCUMENTS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; &lt;br/&gt;&lt;br/&gt;&lt;b&gt;Sortable by:&lt;/b&gt; &lt;code&gt;createddate&lt;/code&gt;, &lt;code&gt;lastmodifieddatetime&lt;/code&gt;, &lt;code&gt;id&lt;/code&gt;
  # @param entity_type Filters results to documents associated with a specific entity type.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset &#x60;offset&#x60; indicates the position of the first record to return. The offset is zero-based and the default is 0.
  # @option opts [Integer] :limit &#x60;limit&#x60; indicates the maximum number of results to be returned in the response. &#x60;limit&#x60; can range between 1 and 500 and the default is 100.
  # @option opts [Time] :last_modified_date_time_start Filters results to any item modified on or after the date time specified. 
  # @option opts [Time] :last_modified_date_time_end Filters results to any item modified on or prior to the date time specified. 
  # @option opts [String] :orderby Indicates the field(s) and direction to sort the results in the response.
  # @option opts [Integer] :entity_id Filters results to documents associated with a specific entity id. entity ID is not required for “DESKTOP” and “OTHER”. Remaining entities need “entity ID”.
  # @return [Array<Document>]
  describe 'retrieve_all_documents test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_document
  # Retrieve a document
  # Retrieves the metadata of a specific document.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;DOCUMENTS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param document_id ID of the document to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Document]
  describe 'retrieve_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_document
  # Update a document
  # Updates the metadata of a specific document.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;DOCUMENTS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param document_id ID of the document to be updated
  # @param update_document updateDocument
  # @param [Hash] opts the optional parameters
  # @return [Document]
  describe 'update_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upload_document
  # Upload a document
  # Upload a document&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;DOCUMENTS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param entity_id Unique identifier of an entity document is attached to.
  # @param entity_type Entity type Document is attached to (Asset, Bill, Bank Deposit, Building, Desktop, Lease, Owner, Portfolio, Prospect, Prospect Contact, Tenant, Unit, Vendor, Check, Credit, Service Agreement, Journal Entry, Work Order)
  # @param file file
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :publish_to_tenant_portal Indicates if the document is published to the tenant portal.
  # @option opts [Boolean] :publish_to_owner_portal Indicates if the document is published to the owner portal.
  # @return [Document]
  describe 'upload_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
