=begin
#Open API, powered by Propertyware


The version of the OpenAPI document: 1.0
Contact: support@propertyware.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Propertyware::PortfoliosApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PortfoliosApi' do
  before do
    # run before each test
    @api_instance = Propertyware::PortfoliosApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PortfoliosApi' do
    it 'should create an instance of PortfoliosApi' do
      expect(@api_instance).to be_instance_of(Propertyware::PortfoliosApi)
    end
  end

  # unit tests for create_portfolio
  # Create a portfolio
  # Creates a portfolio.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PORTFOLIOS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param save_portfolio savePortfolio
  # @param [Hash] opts the optional parameters
  # @return [Portfolio]
  describe 'create_portfolio test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_portfolios
  # Create Portfolios in bulk
  # Creates Portfolios in bulk.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PORTFOLIOS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param save_portfolio savePortfolio
  # @param [Hash] opts the optional parameters
  # @return [Array<RESTAPIBulkSuccessResponse>]
  describe 'create_portfolios test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_portfolio_conversation
  # Delete a portfolio conversation (BETA)
  # &lt;p class&#x3D;\&quot;betaError\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;Write access is only available to customers who have opted in to our beta program. Please reach out to support if you&#39;d like to be included.&lt;/p&gt; Deletes a specific portfolio conversation.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PORTFOLIOS&lt;/span&gt; - &lt;code&gt;Delete&lt;/code&gt; 
  # @param portfolio_id Portfolio ID
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'delete_portfolio_conversation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_portfolio
  # Retrieve a portfolio
  # Retrieves a specific portfolio.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PORTFOLIOS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param portfolio_id Portfolio ID
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_custom_fields includeCustomFields
  # @return [Portfolio]
  describe 'get_portfolio test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_portfolio_conversation
  # Retrieve a portfolio conversation
  # Retrieves a specific portfolio conversation.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PORTFOLIOS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param portfolio_id Portfolio ID
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [Conversation]
  describe 'get_portfolio_conversation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_portfolio_conversations
  # Retrieve all portfolio conversations
  # Retrieves all the conversations of a portfolio.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PORTFOLIOS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; &lt;br/&gt;&lt;br/&gt;&lt;b&gt;Sortable by:&lt;/b&gt; &lt;code&gt;createddate&lt;/code&gt;, &lt;code&gt;lastmodifieddatetime&lt;/code&gt;, &lt;code&gt;id&lt;/code&gt;
  # @param portfolio_id Portfolio ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset &#x60;offset&#x60; indicates the position of the first record to return. The offset is zero-based and the default is 0.
  # @option opts [Integer] :limit &#x60;limit&#x60; indicates the maximum number of results to be returned in the response. &#x60;limit&#x60; can range between 1 and 500 and the default is 100.
  # @option opts [Time] :last_modified_date_time_start Filters results to any item modified on or after the date time specified. 
  # @option opts [Time] :last_modified_date_time_end Filters results to any item modified on or prior to the date time specified. 
  # @option opts [String] :orderby Indicates the field(s) and direction to sort the results in the response.
  # @option opts [String] :type Filters results by the conversation type.
  # @return [Array<Conversation>]
  describe 'get_portfolio_conversations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_portfolios
  # Retrieve all portfolios
  # Retrieves a list of portfolios.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PORTFOLIOS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; &lt;br/&gt;&lt;br/&gt;&lt;b&gt;Sortable by:&lt;/b&gt; &lt;code&gt;createddate&lt;/code&gt;, &lt;code&gt;name&lt;/code&gt;, &lt;code&gt;abbreviation&lt;/code&gt;, &lt;code&gt;lastmodifieddatetime&lt;/code&gt;, &lt;code&gt;id&lt;/code&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset &#x60;offset&#x60; indicates the position of the first record to return. The offset is zero-based and the default is 0.
  # @option opts [Integer] :limit &#x60;limit&#x60; indicates the maximum number of results to be returned in the response. &#x60;limit&#x60; can range between 1 and 500 and the default is 100.
  # @option opts [Time] :last_modified_date_time_start Filters results to any item modified on or after the date time specified. 
  # @option opts [Time] :last_modified_date_time_end Filters results to any item modified on or prior to the date time specified. 
  # @option opts [String] :orderby Indicates the field(s) and direction to sort the results in the response.
  # @option opts [Boolean] :include_deactivated Filters results to portfolios with a deactivated records.
  # @option opts [Boolean] :include_custom_fields includeCustomFields
  # @return [Array<Portfolio>]
  describe 'get_portfolios test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_portfolio
  # Update a portfolio custom fields (BETA)
  # &lt;p class&#x3D;\&quot;betaError\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;Write access is only available to customers who have opted in to our beta program. Please reach out to support if you&#39;d like to be included.&lt;/p&gt; Updates an existing portfolio custom fields&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PORTFOLIOS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param save_custom_field saveCustomField
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'update_portfolio test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_portfolio_using_put1
  # Update a portfolio
  # Updates an existing portfolio.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PORTFOLIOS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param portfolio_id Portfolio ID
  # @param save_portfolio savePortfolio
  # @param [Hash] opts the optional parameters
  # @return [Portfolio]
  describe 'update_portfolio_using_put1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
