=begin
#Open API, powered by Propertyware


The version of the OpenAPI document: 1.0
Contact: support@propertyware.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Propertyware::ProspectsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProspectsApi' do
  before do
    # run before each test
    @api_instance = Propertyware::ProspectsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProspectsApi' do
    it 'should create an instance of ProspectsApi' do
      expect(@api_instance).to be_instance_of(Propertyware::ProspectsApi)
    end
  end

  # unit tests for create_contacts_using_post2
  # Create prospects in bulk
  # Creates prospects in bulk.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;UNITS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param save_prospect saveProspect
  # @param [Hash] opts the optional parameters
  # @return [Array<RESTAPIBulkSuccessResponse>]
  describe 'create_contacts_using_post2 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_prospect
  # Create a prospect
  # Creates a specific prospect.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PROSPECTS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param save_prospect saveProspect
  # @param [Hash] opts the optional parameters
  # @return [Prospect]
  describe 'create_prospect test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_prospect_conversation
  # Create a prospect conversation
  # Creates a specific prospect conversation.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PROSPECTS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param prospect_id Prospect ID
  # @param save_conversation saveConversation
  # @param [Hash] opts the optional parameters
  # @return [Conversation]
  describe 'create_prospect_conversation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_prospect_conversation
  # Delete a prospect conversation (BETA)
  # &lt;p class&#x3D;\&quot;betaError\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;Write access is only available to customers who have opted in to our beta program. Please reach out to support if you&#39;d like to be included.&lt;/p&gt; Deletes a specific prospect conversation.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PROSPECTS&lt;/span&gt; - &lt;code&gt;Delete&lt;/code&gt; 
  # @param prospect_id Prospect ID
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'delete_prospect_conversation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_prospect
  # Retrieve a prospect
  # Retrieves a specific prospect.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PROSPECTS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param prospect_id Prospect ID
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_custom_fields includeCustomFields
  # @return [Prospect]
  describe 'get_prospect test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_prospect_campaign
  # Retrieve prospect campaign
  # Retrieves the campaign details of a prospect.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PROSPECTS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param prospect_id Prospect ID
  # @param [Hash] opts the optional parameters
  # @return [Campaign]
  describe 'get_prospect_campaign test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_prospect_conversation
  # Retrieve a prospect conversation
  # Retrieves a specific prospect conversation.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PROSPECTS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param prospect_id Prospect ID
  # @param conversation_id Conversation ID
  # @param [Hash] opts the optional parameters
  # @return [Conversation]
  describe 'get_prospect_conversation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_prospect_conversations
  # Retrieve all prospect conversations
  # Retrieves all the conversations of a prospect.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PROSPECTS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; &lt;br/&gt;&lt;br/&gt;&lt;b&gt;Sortable by:&lt;/b&gt; &lt;code&gt;createddate&lt;/code&gt;, &lt;code&gt;lastmodifieddatetime&lt;/code&gt;, &lt;code&gt;id&lt;/code&gt;
  # @param prospect_id Prospect ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset &#x60;offset&#x60; indicates the position of the first record to return. The offset is zero-based and the default is 0.
  # @option opts [Integer] :limit &#x60;limit&#x60; indicates the maximum number of results to be returned in the response. &#x60;limit&#x60; can range between 1 and 500 and the default is 100.
  # @option opts [Time] :last_modified_date_time_start Filters results to any item modified on or after the date time specified. 
  # @option opts [Time] :last_modified_date_time_end Filters results to any item modified on or prior to the date time specified. 
  # @option opts [String] :orderby Indicates the field(s) and direction to sort the results in the response.
  # @option opts [String] :type Filters results by the conversation type.
  # @return [Array<Conversation>]
  describe 'get_prospect_conversations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_prospect_statuses
  # Retrieve all prospect statuses
  # Retrieves a list of all prospect statuses&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PROSPECTS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param [Hash] opts the optional parameters
  # @return [Array<ProspectStatus>]
  describe 'get_prospect_statuses test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_prospects
  # Retrieve all prospects
  # Retrieves a list of prospects.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PROSPECTS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; &lt;br/&gt;&lt;br/&gt;&lt;b&gt;Sortable by:&lt;/b&gt; &lt;code&gt;createddate&lt;/code&gt;, &lt;code&gt;type&lt;/code&gt;, &lt;code&gt;lastmodifieddatetime&lt;/code&gt;, &lt;code&gt;status&lt;/code&gt;, &lt;code&gt;id&lt;/code&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset &#x60;offset&#x60; indicates the position of the first record to return. The offset is zero-based and the default is 0.
  # @option opts [Integer] :limit &#x60;limit&#x60; indicates the maximum number of results to be returned in the response. &#x60;limit&#x60; can range between 1 and 500 and the default is 100.
  # @option opts [Time] :last_modified_date_time_start Filters results to any item modified on or after the date time specified. 
  # @option opts [Time] :last_modified_date_time_end Filters results to any item modified on or prior to the date time specified. 
  # @option opts [String] :orderby Indicates the field(s) and direction to sort the results in the response.
  # @option opts [String] :status Filters results to prospects with a specific status.
  # @option opts [Integer] :portfolio_id Filters results to prospects associated with a specific portfolio.
  # @option opts [Integer] :building_id Filters results to prospects associated with a specific building.
  # @option opts [String] :type Filters results to prospects with a specific type.
  # @option opts [Boolean] :include_custom_fields includeCustomFields
  # @return [Array<Prospect>]
  describe 'get_prospects test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_lease_using_put2
  # Update a prospect custom fields (BETA)
  # &lt;p class&#x3D;\&quot;betaError\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;Write access is only available to customers who have opted in to our beta program. Please reach out to support if you&#39;d like to be included.&lt;/p&gt; Updates an existing prospect custom fields&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;PROSPECTS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param save_custom_field saveCustomField
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'update_lease_using_put2 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
