=begin
#Open API, powered by Propertyware


The version of the OpenAPI document: 1.0
Contact: support@propertyware.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Propertyware::WorkOrdersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WorkOrdersApi' do
  before do
    # run before each test
    @api_instance = Propertyware::WorkOrdersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkOrdersApi' do
    it 'should create an instance of WorkOrdersApi' do
      expect(@api_instance).to be_instance_of(Propertyware::WorkOrdersApi)
    end
  end

  # unit tests for add_work_order_task_comments
  # Add Comments to task for a workOrder
  # Add Comments to task for WorkOrder.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param work_order_id Work Order ID
  # @param task_id Task ID
  # @param save_comment saveComment
  # @param [Hash] opts the optional parameters
  # @return [Task]
  describe 'add_work_order_task_comments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for close_work_order
  # Close a Workorder  (BETA)
  # &lt;p class&#x3D;\&quot;betaError\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;Write access is only available to customers who have opted in to our beta program. Please reach out to support if you&#39;d like to be included.&lt;/p&gt; Close an existing Workorder&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param work_order_id WorkOrder ID
  # @param close_work_order closeWorkOrder
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'close_work_order test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_work_order
  # Create a work order
  # Creates a work order.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param save_work_order saveWorkOrder
  # @param [Hash] opts the optional parameters
  # @return [WorkOrder]
  describe 'create_work_order test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_work_order_task
  # Create a task to workOrder
  # Create a task to an workOrder.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param work_order_id Work Order ID
  # @param save_work_order_task saveWorkOrderTask
  # @param [Hash] opts the optional parameters
  # @return [Task]
  describe 'create_work_order_task test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_work_orders
  # Create work orders in bulk
  # Creates word orders in bulk.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param save_work_order saveWorkOrder
  # @param [Hash] opts the optional parameters
  # @return [Array<RESTAPIBulkSuccessResponse>]
  describe 'create_work_orders test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_work_order
  # Delete a Work Order (BETA)
  # &lt;p class&#x3D;\&quot;betaError\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;Write access is only available to customers who have opted in to our beta program. Please reach out to support if you&#39;d like to be included.&lt;/p&gt; Delete a Work Order.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Delete&lt;/code&gt; 
  # @param work_order_id Work Order ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'delete_work_order test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_work_order_task
  # Delete a work order task (BETA)
  # &lt;p class&#x3D;\&quot;betaError\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;Write access is only available to customers who have opted in to our beta program. Please reach out to support if you&#39;d like to be included.&lt;/p&gt; Deletes a specific work order task.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Delete&lt;/code&gt; 
  # @param work_order_id Work Order ID
  # @param task_id Task ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'delete_work_order_task test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_work_order
  # Retrieve a work order
  # Retrieves a specific work order.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param work_order_id Work Order ID
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_custom_fields includeCustomFields
  # @return [WorkOrder]
  describe 'get_work_order test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_work_order_task
  # Retrieve a work order task
  # Retrieves a specific work order task.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; 
  # @param work_order_id Work Order ID
  # @param task_id Task ID
  # @param [Hash] opts the optional parameters
  # @return [Array<Task>]
  describe 'get_work_order_task test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_work_order_tasks
  # Retrieve all work order tasks
  # Retrieves a list of work order tasks.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; &lt;br/&gt;&lt;br/&gt;&lt;b&gt;Sortable by:&lt;/b&gt; &lt;code&gt;createddate&lt;/code&gt;, &lt;code&gt;lastmodifieddatetime&lt;/code&gt;, &lt;code&gt;id&lt;/code&gt;
  # @param work_order_id Work Order ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset &#x60;offset&#x60; indicates the position of the first record to return. The offset is zero-based and the default is 0.
  # @option opts [Integer] :limit &#x60;limit&#x60; indicates the maximum number of results to be returned in the response. &#x60;limit&#x60; can range between 1 and 500 and the default is 100.
  # @option opts [Time] :last_modified_date_time_start Filters results to any item modified on or after the date time specified. 
  # @option opts [Time] :last_modified_date_time_end Filters results to any item modified on or prior to the date time specified. 
  # @option opts [String] :orderby Indicates the field(s) and direction to sort the results in the response.
  # @option opts [Date] :due_date Filters results by due day.
  # @option opts [Boolean] :completed Filters results by task status.
  # @return [Array<Task>]
  describe 'get_work_order_tasks test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_work_orders
  # Retrieve all work orders
  # Retrieves a list of work orders.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Read&lt;/code&gt; &lt;br/&gt;&lt;br/&gt;&lt;b&gt;Sortable by:&lt;/b&gt; &lt;code&gt;createddate&lt;/code&gt;, &lt;code&gt;number&lt;/code&gt;, &lt;code&gt;type&lt;/code&gt;, &lt;code&gt;lastmodifieddatetime&lt;/code&gt;, &lt;code&gt;status&lt;/code&gt;, &lt;code&gt;id&lt;/code&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset &#x60;offset&#x60; indicates the position of the first record to return. The offset is zero-based and the default is 0.
  # @option opts [Integer] :limit &#x60;limit&#x60; indicates the maximum number of results to be returned in the response. &#x60;limit&#x60; can range between 1 and 500 and the default is 100.
  # @option opts [Time] :last_modified_date_time_start Filters results to any item modified on or after the date time specified. 
  # @option opts [Time] :last_modified_date_time_end Filters results to any item modified on or prior to the date time specified. 
  # @option opts [String] :orderby Indicates the field(s) and direction to sort the results in the response.
  # @option opts [Integer] :portfolio_id Filters results to prospects associated with a specific portfolio.
  # @option opts [Integer] :building_id Filters results to prospects associated with a specific building.
  # @option opts [String] :status Filters results to work orders with a specific status.
  # @option opts [String] :type Filters results to work orders with a specific type.
  # @option opts [String] :priority Filters results to work orders with a specific priority.
  # @option opts [Date] :completed_date_start Filters results to any payment with a date on or after to the date specified.
  # @option opts [Date] :completed_date_end Filters results to any payment with a date on or prior to the date specified.
  # @option opts [Boolean] :include_custom_fields includeCustomFields
  # @return [Array<WorkOrder>]
  describe 'get_work_orders test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_work_order
  # Update a workorder custom fields (BETA)
  # &lt;p class&#x3D;\&quot;betaError\&quot;&gt;&lt;b&gt;Note: &lt;/b&gt;Write access is only available to customers who have opted in to our beta program. Please reach out to support if you&#39;d like to be included.&lt;/p&gt; Updates an existing workorder custom fields&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param save_custom_field saveCustomField
  # @param [Hash] opts the optional parameters
  # @return [ResponseEntity]
  describe 'update_work_order test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_work_order_task
  # Update a task in workOrder
  # Update an existing workOrder task.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Required permission:&lt;/b&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;permissionBlock\&quot;&gt;WORK ORDERS&lt;/span&gt; - &lt;code&gt;Write&lt;/code&gt; 
  # @param work_order_id Work Order ID
  # @param task_id Task ID
  # @param save_work_order_task saveWorkOrderTask
  # @param [Hash] opts the optional parameters
  # @return [Task]
  describe 'update_work_order_task test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
