=begin
#Open API, powered by Propertyware


The version of the OpenAPI document: 1.0
Contact: support@propertyware.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module Propertyware
  # Bill
  class Bill
    # Amount.
    attr_accessor :amount

    # Entry date.
    attr_accessor :bill_date

    # Number.
    attr_accessor :bill_number

    # List of bill splits.
    attr_accessor :bill_splits

    # Description.
    attr_accessor :comments

    # User who created the record.
    attr_accessor :created_by

    # Date and time the record was created. (Timezone: UTC)
    attr_accessor :created_date_time

    # Indicates if the bill is a vendor credit.
    attr_accessor :credit

    # Due date.
    attr_accessor :due_date

    # List of expense recoveries
    attr_accessor :expense_recoveries

    # Unique identifier.
    attr_accessor :id

    # User who last modified the record.
    attr_accessor :last_modified_by

    # Date and time the record was last modified. (Timezone: UTC)
    attr_accessor :last_modified_date_time

    # The ID of the markup/discount general ledger account associated with the bill.
    attr_accessor :markup_gl_account_id

    # The markup percentage.
    attr_accessor :markup_percentage

    # Date the bill was paid.
    attr_accessor :payment_date

    # Reference number.
    attr_accessor :ref_no

    # Bill terms.
    attr_accessor :terms

    # The ID of the vendor related to the bill.
    attr_accessor :vendor_id

    # The ID of the work order associated with the bill.
    attr_accessor :work_order_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'amount' => :'amount',
        :'bill_date' => :'billDate',
        :'bill_number' => :'billNumber',
        :'bill_splits' => :'billSplits',
        :'comments' => :'comments',
        :'created_by' => :'createdBy',
        :'created_date_time' => :'createdDateTime',
        :'credit' => :'credit',
        :'due_date' => :'dueDate',
        :'expense_recoveries' => :'expenseRecoveries',
        :'id' => :'id',
        :'last_modified_by' => :'lastModifiedBy',
        :'last_modified_date_time' => :'lastModifiedDateTime',
        :'markup_gl_account_id' => :'markupGLAccountID',
        :'markup_percentage' => :'markupPercentage',
        :'payment_date' => :'paymentDate',
        :'ref_no' => :'refNo',
        :'terms' => :'terms',
        :'vendor_id' => :'vendorID',
        :'work_order_id' => :'workOrderID'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'amount' => :'Float',
        :'bill_date' => :'Date',
        :'bill_number' => :'Integer',
        :'bill_splits' => :'Array<BillSplit>',
        :'comments' => :'String',
        :'created_by' => :'String',
        :'created_date_time' => :'Time',
        :'credit' => :'Boolean',
        :'due_date' => :'Date',
        :'expense_recoveries' => :'Array<ExpenseRecoveryCharge>',
        :'id' => :'Integer',
        :'last_modified_by' => :'String',
        :'last_modified_date_time' => :'Time',
        :'markup_gl_account_id' => :'Integer',
        :'markup_percentage' => :'Float',
        :'payment_date' => :'Date',
        :'ref_no' => :'String',
        :'terms' => :'String',
        :'vendor_id' => :'Integer',
        :'work_order_id' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Propertyware::Bill` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Propertyware::Bill`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'bill_date')
        self.bill_date = attributes[:'bill_date']
      end

      if attributes.key?(:'bill_number')
        self.bill_number = attributes[:'bill_number']
      end

      if attributes.key?(:'bill_splits')
        if (value = attributes[:'bill_splits']).is_a?(Array)
          self.bill_splits = value
        end
      end

      if attributes.key?(:'comments')
        self.comments = attributes[:'comments']
      end

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      end

      if attributes.key?(:'created_date_time')
        self.created_date_time = attributes[:'created_date_time']
      end

      if attributes.key?(:'credit')
        self.credit = attributes[:'credit']
      end

      if attributes.key?(:'due_date')
        self.due_date = attributes[:'due_date']
      end

      if attributes.key?(:'expense_recoveries')
        if (value = attributes[:'expense_recoveries']).is_a?(Array)
          self.expense_recoveries = value
        end
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'last_modified_by')
        self.last_modified_by = attributes[:'last_modified_by']
      end

      if attributes.key?(:'last_modified_date_time')
        self.last_modified_date_time = attributes[:'last_modified_date_time']
      end

      if attributes.key?(:'markup_gl_account_id')
        self.markup_gl_account_id = attributes[:'markup_gl_account_id']
      end

      if attributes.key?(:'markup_percentage')
        self.markup_percentage = attributes[:'markup_percentage']
      end

      if attributes.key?(:'payment_date')
        self.payment_date = attributes[:'payment_date']
      end

      if attributes.key?(:'ref_no')
        self.ref_no = attributes[:'ref_no']
      end

      if attributes.key?(:'terms')
        self.terms = attributes[:'terms']
      end

      if attributes.key?(:'vendor_id')
        self.vendor_id = attributes[:'vendor_id']
      end

      if attributes.key?(:'work_order_id')
        self.work_order_id = attributes[:'work_order_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          amount == o.amount &&
          bill_date == o.bill_date &&
          bill_number == o.bill_number &&
          bill_splits == o.bill_splits &&
          comments == o.comments &&
          created_by == o.created_by &&
          created_date_time == o.created_date_time &&
          credit == o.credit &&
          due_date == o.due_date &&
          expense_recoveries == o.expense_recoveries &&
          id == o.id &&
          last_modified_by == o.last_modified_by &&
          last_modified_date_time == o.last_modified_date_time &&
          markup_gl_account_id == o.markup_gl_account_id &&
          markup_percentage == o.markup_percentage &&
          payment_date == o.payment_date &&
          ref_no == o.ref_no &&
          terms == o.terms &&
          vendor_id == o.vendor_id &&
          work_order_id == o.work_order_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [amount, bill_date, bill_number, bill_splits, comments, created_by, created_date_time, credit, due_date, expense_recoveries, id, last_modified_by, last_modified_date_time, markup_gl_account_id, markup_percentage, payment_date, ref_no, terms, vendor_id, work_order_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Propertyware.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
